# Node.js with React
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial(4d7ef7c9-922b-406b-a998-494b8abc07a7)'
    appType: 'webAppLinux'
    WebAppName: 'ragunanthanTodo'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
